#! /bin/bash

### BEGIN INIT INFO
# Provides:          check_url
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     3 4 5
# Default-Stop:      0 1 6
# Short-Description: check_url service
# Description:       Run check_url service
### END INIT INFO


DAEMON=/opt/check_url/check_url.py
PIDFILE=/var/run/check_url.py.pid
NAME=check_url

. /lib/lsb/init-functions


case "$1" in
  start)
    log_daemon_msg "starting" "check_url"
    start-stop-daemon --start --background \
                      --exec "$DAEMON" \
                      --pidfile "$PIDFILE" \
                      --make-pidfile
    ;;
  stop)
    log_daemon_msg "stopping" "check_url"
    killproc -p "$PIDFILE" "$DAEMON"
    ;;
  restart)
    log_daemon_msg "restarting" "check_url"
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME"
    ;;
  *)
    echo "Usage: /etc/init.d/check_url {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
